<a href="https://colab.research.google.com/github/hyeongjin0706/dataanalysis/blob/1_Numpy/1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. 넘파이(Numpy)
* 수학, 과학 계산용 패키지
* 자료구조(**ndarray**)를 제공 -> 파이썬의 list보다 속도가 빠름, 적은 메모리를 사용

numpy 설치

In [ ]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


numpy 사용

In [ ]:
import numpy

라이브러리 위치

In [ ]:
numpy

<module 'numpy' from '/usr/local/lib/python3.10/dist-packages/numpy/__init__.py'>

In [ ]:
import numpy as np

In [ ]:
np

<module 'numpy' from '/usr/local/lib/python3.10/dist-packages/numpy/__init__.py'>

### 1-1. ndarray

In [ ]:
list1 = [1, 2, 3, 4]
list2 = [[1,2,3,4], [5,6,7,8]]
print(list1)
print(list2)
print(type(list1))
print(type(list1[0]))
print(type(list2))

[1, 2, 3, 4]
[[1, 2, 3, 4], [5, 6, 7, 8]]
<class 'list'>
<class 'int'>
<class 'list'>


In [ ]:
ndarr1 = np.array([1,2,3,4])
print(ndarr1)
print(type(ndarr1)) # ndarray = n dimension array

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
# 리스트를 ndarray로 변환하는 방법
ndarr1 = np.array(list1)
ndarr2 = np.array(list2)

print(ndarr1)
print(ndarr2)
print(type(ndarr1))
print(type(ndarr2))

[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


### 1-2. ndarray의 data type
* ndarray는 list와 다르게 1개의 단일 데이터 타입만 허용

In [ ]:
list1 = [1, 3.14, "python", "😎", True]

In [ ]:
list1

[1, 3.14, 'python', '😎', True]

In [ ]:
list1[3]

'😎'

In [ ]:
ndarr1 = np.array([1,2,3,4])

In [ ]:
ndarr1

array([1, 2, 3, 4])

In [ ]:
ndarr2 = np.array([1,2,3.14,4]) # 모든 요소가 float로 변경됨

In [ ]:
ndarr2

array([1.  , 2.  , 3.14, 4.  ])

In [ ]:
ndarr3 = np.array([1,2,3.14, True]) # 모든 요소가 float로 변경됨

In [ ]:
ndarr3

array([1.  , 2.  , 3.14, 1.  ])

In [ ]:
ndarr4 = np.array(["1",2,3.14, True]) # 모든 요소가 string로 변경됨

In [ ]:
ndarr4 # dtype='<U32' 유니코드 데이터 타입

array(['1', '2', '3.14', 'True'], dtype='<U32')

In [ ]:
type(ndarr4)

numpy.ndarray

In [ ]:
ndarr3 = np.array([1,2,3.14, True], dtype=int) # datatype을 int로 설정

In [ ]:
ndarr3

array([1, 2, 3, 1])

In [ ]:
ndarr4 = np.array(["1",2,3.14, True], dtype=int) # datatype을 int로 설정

In [ ]:
ndarr4

array([1, 2, 3, 1])

In [ ]:
ndarr5 = np.array(["1",2,"3.14", True], dtype=int) # 3.14를 바꾸지 못함

ValueError: ignored

### 1-3. ndarray 슬라이싱

In [ ]:
ndarr1 = np.array(['🍒','🍑','🍐','🍏'])
ndarr1

array(['🍒', '🍑', '🍐', '🍏'], dtype='<U1')

In [ ]:
ndarr1.shape # ndarray에 저장되어있는 행렬을 보여줌

(4,)

In [ ]:
# 인덱싱
print(ndarr1[0])
print(ndarr1[3])
print(ndarr1[-1])
print(ndarr1[-2])

🍒
🍏
🍏
🍐


In [ ]:
# 슬라이싱 ['🍒','🍑','🍐','🍏']
print(ndarr1[0:3])
print(ndarr1[1:])
print(ndarr1[:3])

['🍒' '🍑' '🍐']
['🍑' '🍐' '🍏']
['🍒' '🍑' '🍐']


In [ ]:
ndarr2d = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
ndarr2d.shape # (3, 4) 3행 4열


(3, 4)

In [ ]:
print(ndarr2d[0,2]) # 3
print(ndarr2d[0][2]) # 3

3
3


In [ ]:
# 0행 가져오기
print(ndarr2d[0]) # [1 2 3 4] 자주 사용하는 방법
print(ndarr2d[0,]) # [1 2 3 4] 
print(ndarr2d[0,:]) # [1 2 3 4] 자주 사용하는 방법

[1 2 3 4]
[1 2 3 4]
[1 2 3 4]


In [ ]:
# 0열 가져오기
# 앞의 행은 다 가져오고 , 0열을 가져옴
print(ndarr2d[:,0]) # [1 5 9]

[1 5 9]


### 1-4. Fancy 인덱싱
* 범위가 아닌 특정 index의 집합의 값들을 선택해서 추출하고 싶을 때 활용

In [ ]:
ndarr1 = np.array([10,15,2,8,20,90,85,44,23,32])

In [ ]:
idx = [2, 5, 9]

In [ ]:
# 인덱스의 넣는 숫자
ndarr1[idx] # array([ 2, 90, 32])

array([ 2, 90, 32])

In [ ]:
ndarr2d = np.array([[1,2,3,4], 
                    [5,6,7,8], 
                    [9,10,11,12]])

In [ ]:
ndarr2d[[0,1],:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### 1-5. Boolean 인덱싱
* 조건에 대한 필터링을 통해 Boolean 값을 이용한 색인을 사용

In [ ]:
ndarr1 = np.array(['🍒','🍑','🍐','🍏','🍕'])
selValue = [True, False, True, True, False]

In [ ]:
# 중요! True인것만 뽑힘
ndarr1[selValue] # array(['🍒', '🍐', '🍏'], dtype='<U1')

array(['🍒', '🍐', '🍏'], dtype='<U1')

In [ ]:
selValue = [True, False, True]

In [ ]:
ndarr1[selValue] # 숫자가 맞지 않기 때문에 에러 발생!

IndexError: ignored

In [ ]:
ndarr2d = np.array([[1,2,3,4], 
                    [5,6,7,8], 
                    [9,10,11,12]])

In [ ]:
ndarr2d > 7 #boolean화가 되어 7보다 큰 값들만 True로 표현

array([[False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True]])

In [ ]:
ndarr2d[ndarr2d > 7] # 7보다 큰 값들만 뽑힘

array([ 8,  9, 10, 11, 12])

# 2. 행렬 연산

### 2-1. 연산자
* 덧셈, 뺄셈, 곱셈, 나눗셈은 shape가 같아야 함
* 같은 postition끼리 연산
* 내적(dot product)은 맞닿는 shape가 같아야 함
* 내적은 떨어져 있는 shape가 결과 행렬이 됨

In [ ]:
a = np.array([[1,2,3],
             [2,3,4]])
b = np.array([[3,4,5],
             [1,2,3]])

a.shape, b.shape

((2, 3), (2, 3))

In [ ]:
# 덧셈연산
a + b

# array([[4, 6, 8],
#      [3, 5, 7]])

array([[4, 6, 8],
       [3, 5, 7]])

In [ ]:
# a = np.array([[1,2,3],
#              [2,3,4]])
# b = np.array([[3,4,5],
#              [1,2,3]])

# a + b shpae가 다르므로 에러

In [ ]:
# 뺄셈 연산
a - b

array([[-2, -2, -2],
       [ 1,  1,  1]])

In [ ]:
# 곱셈 연산
a * b

array([[ 3,  8, 15],
       [ 2,  6, 12]])

In [ ]:
# 나눗셈 연산
a / b

array([[0.33333333, 0.5       , 0.6       ],
       [2.        , 1.5       , 1.33333333]])

In [ ]:
# dot product(행렬곱, 내적)
# 영상관련 딥러닝할때 많이 쓰임
a = np.array([[1,2,3],
              [1,2,3],
              [2,3,4]])

b = np.array([[1,2],
              [3,4],
              [5,6]])

In [ ]:
a.shape, b.shape

((3, 3), (3, 2))

In [ ]:
print((1*1 + 2*3 + 3*5), (1*2 + 2*4 + 3*6))
print((1*1 + 2*3 + 3*5), (1*2 + 2*4 + 3*6))
print((2*1 + 3*3 + 4*5), (2*2 + 3*4 + 4*6))

22 28
22 28
31 40


In [ ]:
np.dot(a,b)

array([[22, 28],
       [22, 28],
       [31, 40]])

### 2-2. arange
* 순차적인 값을 생성할 때 사용

In [ ]:
arr1 = range(1, 11)

In [ ]:
arr1

range(1, 11)

In [ ]:
for i in arr1:
    print(i, end=' ')

1 2 3 4 5 6 7 8 9 10 

In [ ]:
arr2 = np.arange(1,11)

In [ ]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
for i in arr2:
    print(i, end=' ')

1 2 3 4 5 6 7 8 9 10 

### 2-3. sort

In [ ]:
ndarr1 = np.array([1,10,5,7,2,4,3,6,8,9])
ndarr1

array([ 1, 10,  5,  7,  2,  4,  3,  6,  8,  9])

In [ ]:
np.sort(ndarr1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ndarr1

array([ 1, 10,  5,  7,  2,  4,  3,  6,  8,  9])

In [ ]:
np.sort(ndarr1, reverse=True) # reverse 속성이 없음

TypeError: ignored

In [ ]:
# 문자열 역순으로 출력하기
str1 = 'Python'
print(str1[:]) # 모든 문자를 슬라이싱
print(str1[::]) # print(str1[::1]) -> 1: 정방향
print(str1[::-1]) # print(str1[::-1]) -> -1 :역방향
print(str1[4:1:-1]) # 4번 인덱스부터 1직전까지 역순으로 가져오기
print(str1[4::-1]) # 4번 인덱스부터 0까지 역순으로 가져오기

Python
Python
nohtyP
oht
ohtyP


In [ ]:
np.sort(ndarr1)[::-1] # 내림차순 정렬

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [ ]:
ndarr2d = np.array([[11,10,12,9],
                   [3,1,4,2],
                   [5,6,7,8]])

In [ ]:
ndarr2d.shape #(3, 4)

(3, 4)

In [ ]:
# 행 정렬(axis=0)
np.sort(ndarr2d, axis=0) 

array([[ 3,  1,  4,  2],
       [ 5,  6,  7,  8],
       [11, 10, 12,  9]])

In [ ]:
# 열 정렬(axis=1)
np.sort(ndarr2d, axis=1)

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [ ]:
np.sort(ndarr2d, axis=1)[:,::-1]

array([[12, 11, 10,  9],
       [ 4,  3,  2,  1],
       [ 8,  7,  6,  5]])

In [ ]:
# 축의 마지막 방향
np.sort(ndarr2d, axis=-1)

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

### 2-4. 숫자의 단일 연산


In [ ]:
a = np.array([[1,2,3],
              [4,5,6]])

In [ ]:
# 모든 요소에 3을 더함
a+3

array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
a-3

array([[-2, -1,  0],
       [ 1,  2,  3]])

In [ ]:
a*3

array([[ 3,  6,  9],
       [12, 15, 18]])

In [ ]:
a/3

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        ]])

In [ ]:
b = np.array([[3,3,3],
             [3,3,3]])

In [ ]:
a+b

array([[4, 5, 6],
       [7, 8, 9]])